### PR TITLE
Update pricing page

### PR DESCRIPTION
**Pull request by tgsoverly**
Screenshot 2023-11-14 at 11 13 39 AM

### CODE REVIEW

**Comment by jpjsonic** [comment]
> ### ✅ Deploy Preview for _visivo-io_ ready!
> Name	Link
> 🔨 Latest commit	[6c756a8](https://github.com/visivo-io/www/commit/6c756a86b5d746d4951bfb7c9b8716da2aa32d51)
> 🔍 Latest deploy log	https://app.netlify.com/sites/visivo-io/deploys/65535693a41d4b000847c99f
> 😎 Deploy Preview	https://deploy-preview-29--visivo-io.netlify.app
> 📱 Preview on mobile	
> Toggle QR Code...
> Lighthouse
> Lighthouse	1 paths audited
> **Performance**: 98
> **Accessibility**: 92
> **Best Practices**: 92
> **SEO**: 92
> **PWA**: -
> [View the detailed breakdown and full score reports](https://app.netlify.com/sites/visivo-io/deploys/65535693a41d4b000847c99f)
> _To edit notification comments on pull requests, go to your [Netlify site configuration](https://app.netlify.com/sites/visivo-io/configuration/deploys#deploy-notifications)._

Woah, these are sweet

**Comment by jpjsonic** [comment]
> Screenshot 2023-11-14 at 11 13 39 AM

@tgsoverly This looks great! A few thoughts: 

* It might be good to add "self host" and "unlimited dashboard" to the Local tier.
* We should consider adding an enterprise tile with with the following items added to the standard ones (priority support, custom implementations, dedicated slack channel)

**Comment by jpjsonic** [comment]
@tgsoverly also what are your thoughts on adding a "Book a Demo" button that opens up an email to support@visivo.io in place of the current "Our Viewpoint" button?

**Comment by tgsoverly** [comment]
@jpjsonic What about book a demo to a calendly page or something?

**Pull request merged**
